name: multisiteacquiaapp
recipe: acquia
services:
  database:
    run:
      - /app/.lando/database-generation.sh

env_file:
  - .lando/multisite.env

proxy:
  appserver:
    - site1.lndo.site
    - site2.lndo.site

tooling:
  pull:
    cmd: /app/.lando/acquia-pull.sh
    options:
      site:
        passthrough: true
        alias:
          - s
        describe: The namespace of the site from which you wish to pull?
        interactive:
          type: list
          message: What is the namespace of the site from which you wish to pull?
          default: all
          choices:
            - all
            - site1
            - site2
          weight: 600
  push: disabled

config:
  webroot: docroot
  acli_version: latest
  ah_application_uuid: someuuid
  ah_site_group: multisiteacquiaapp
  php: '8.1'

